[package]
name = "grove-proxy"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
async-trait.workspace = true
bytes.workspace = true
http.workspace = true
http-body-util.workspace = true
hyper.workspace = true
hyper-util.workspace = true
parking_lot.workspace = true
rcgen = { workspace = true, features = ["x509-parser"] }
rustls.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true
tower-service = "0.3"
tracing.workspace = true

[dev-dependencies]
futures.workspace = true
tempfile.workspace = true
